# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint
      run: |
        poetry run task lint
    - name: Test with pytest
      run: |
        poetry run task test
    - name: Security
      run: |
        poetry run task security
    - name: Format
      run: |
        poetry run task formatter    
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/iac-labs/iac-labs/example-app/.venv
        key: ${{ runner.os }}-venv    
    concurrency:
          group: first-group        
  lint:
      strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      needs: build
      concurrency:
          group: second-group 
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Lint
        run: |
          poetry run task lint        
      - name: load cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/iac-labs/iac-labs/example-app/.venv
          key: ${{ runner.os }}-venv     
  formatter:
      strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      needs: build
      concurrency:
          group: second-group 
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Formatter
        run: |
          poetry run task formatter       
      - name: load cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/iac-labs/iac-labs/example-app/.venv
          key: ${{ runner.os }}-venv      
  security:
      strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      needs: build
      concurrency:
          group: second-group      
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Security
        run: |
          poetry run task security       
      - name: load cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/iac-labs/iac-labs/example-app/.venv
          key: ${{ runner.os }}-venv      
  unittests:
        strategy:
            matrix:
              os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        needs: [lint, formatter, security]
        concurrency:
            group: third-group
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install Poetry
          uses: snok/install-poetry@v1
        - name: Unittests
          run: |
            poetry run task test   
        - name: load cache
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
            path: /home/runner/work/iac-labs/iac-labs/example-app/.venv
            key: ${{ runner.os }}-venv       
