# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint
      run: |
        poetry run task lint
    - name: Test with pytest
      run: |
        poetry run task test
    - name: Security
      run: |
        poetry run task security
    - name: Format
      run: |
        poetry run task formatter     
    concurrency:
          group: first-group        
  lint:
      runs-on: ubuntu-latest
      concurrency:
          group: second-group 
      steps:
      - name: Lint
        run: |
          poetry run task lint    
  formatter:
      runs-on: ubuntu-latest
      concurrency:
          group: second-group 
      steps:
      - name: Formatter
        run: |
          poetry run task formatter       
  security:
      runs-on: ubuntu-latest
      concurrency:
          group: second-group      
      steps:
      - name: Security
        run: |
          poetry run task security       
  unittests:
        runs-on: ubuntu-latest
        concurrency:
            group: third-group
        steps:
        - name: Unittests
          run: |
            poetry run task test     
